Add files via upload
mandiant/capa-rules pull request #612
Opened 2022-08-23 02:36 UTC by johnk3r

Hello,

I'm creating this generic rule so we can discuss the best approach. I look forward to any recommendations/suggestions.

https://github.com/mandiant/capa-rules/issues/609

2022-08-23 08:48 UTC, mr-tz commented
Great, thanks a lot. What do you think of breaking these up into multiple rules?
- use .NET library Costura.Fody
- use .NET library SharpVectors
- use .NET library Newtonsoft.Json
- use .NET library EncryptDecryptUtils
- use .NET library SharpClipboard

This allows us to identify 3rd party library usage more explicitly.

2022-08-24 11:02 UTC, mr-tz requested changes
This is a great start. A few suggestions and comments for discussion.

2022-08-24 11:02 UTC, mr-tz commented on nursery/use-dotnet-library-newtonsoft.json.yml
> +    namespace: nursery
or should we add new namespaces? `linking/library`?

2022-08-24 11:02 UTC, mr-tz commented on nursery/use-dotnet-library-sharpvectors.yml
> +    namespace: nursery
```suggestion
    namespace: data-manipulation/svg
```

2022-08-24 11:02 UTC, mr-tz commented on nursery/use-dotnet-library-sharpvectors.yml
> +    namespace: nursery
looking for other input on this

2022-08-24 11:02 UTC, mr-tz commented on nursery/use-dotnet-library-newtonsoft.json.yml
> +    namespace: nursery
or `data-manipulation/json`?

2022-08-25 02:57 UTC, johnk3r commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +      - string: "RijndaelEncryptDecrypt"
Done. About detection by class or namespace, for the samples I have this was not possible. The libraries are in the "references" section.

2022-08-25 03:05 UTC, johnk3r commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +      - string: "RijndaelEncryptDecrypt"
![2022-08-25 00_04_55-use  NET libraries · mandiant_capa-rules@cd7d705](https://user-images.githubusercontent.com/6247648/186565016-5a71885f-7d8a-4fc9-9e59-3728400f451a.png)

Can I disregard this?

2022-08-25 03:13 UTC, johnk3r commented on nursery/use-dotnet-library-newtonsoft.json.yml
> +    namespace: nursery
"data-manipulation/json" seems more suitable to me.

2022-08-25 10:55 UTC, mr-tz commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +      - string: "RijndaelEncryptDecrypt"
Please quote the string again per the linter.

2022-08-25 10:57 UTC, mr-tz commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +      - string: "RijndaelEncryptDecrypt"
@mike-hunhoff is this already tracked as a possible improvement? maybe not worth adding if we can just get away with string, of course.

2022-08-25 11:05 UTC, mr-tz requested changes
thanks, we're getting close now!

2022-08-25 11:05 UTC, mr-tz commented on collection/use-dotnet-library-sharpclipboard.yml
> +      - string: SharpClipboard
```suggestion
      - string: "SharpClipboard"
```

2022-08-25 11:05 UTC, mr-tz commented on collection/use-dotnet-library-sharpclipboard.yml
> +      - string: SharpClipboard
sorry, my bad!

2022-08-25 11:05 UTC, mr-tz commented on data-manipulation/json/use-dotnet-library-newtonsoftjson.yml
> +      - string: Newtonsoft.Json
```suggestion
      - string: "Newtonsoft.Json"
```

2022-08-25 11:05 UTC, mr-tz commented on data-manipulation/svg/use-dotnet-library-sharpvectors.yml
> +      - string: SharpVectors.Converters.Wpf
```suggestion
      - string: "SharpVectors.Converters.Wpf"
```

2022-08-25 11:05 UTC, mr-tz commented on data-manipulation/encryption/aes/use-dotnet-library-encryptdecryptutils.yml
> +      - string: RijndaelEncryptDecrypt
```suggestion
      - string: "RijndaelEncryptDecrypt"
```

2022-08-25 11:05 UTC, mr-tz commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +    namespace: anti-analysis/obfuscation
Do you think this is obfuscation vs. encryption?

2022-08-25 11:05 UTC, mr-tz commented on nursery/use-dotnet-library-sharpvectors.yml
> +    namespace: nursery
still TODO, `nursery` is not a "valid" namespace
@mike-hunhoff?

2022-08-27 15:52 UTC, johnk3r commented on anti-analysis/obfuscation/use-dotnet-library-encryptdecryptutils.yml
> +    namespace: anti-analysis/obfuscation
My bad.

2022-08-29 11:51 UTC, mr-tz requested changes
one last change to make authors a list, then GTG!

2022-08-29 11:51 UTC, mr-tz commented on executable/resource/embed-dependencies-as-resources-using-fodycostura.yml
> +      - johnk3r, moritz.raabe@mandiant.com
```suggestion
      - johnk3r
      - "@mr-tz"
```

2022-08-29 11:51 UTC, mr-tz commented on executable/resource/embed-dependencies-as-resources-using-fodycostura.yml
> +      - johnk3r, moritz.raabe@mandiant.com
thanks :)

2022-08-29 14:29 UTC, johnk3r commented on executable/resource/embed-dependencies-as-resources-using-fodycostura.yml
> +      - johnk3r, moritz.raabe@mandiant.com
I think it's ok now!

2022-08-29 16:49 UTC, mr-tz approved these changes

2022-08-29 16:49 UTC, merged

2022-08-29 16:49 UTC, mr-tz commented
Awesome, thanks a lot, @johnk3r!!!