Rule for lzo encryption
mandiant/capa-rules pull request #623
Opened 2022-09-16 20:15 UTC by edeca

Work in progress rule for LZO encryption. Found in a sample which requires manual unpacking, therefore looking for alternate samples.

Further work needed before merging.

2022-09-16 20:58 UTC, edeca commented
[PR for sample file](https://github.com/mandiant/capa-testfiles/pull/143).

2022-09-16 22:01 UTC, edeca commented
Ready for review. CI needs the sample file merged to pass.

2022-09-19 14:47 UTC, mr-tz requested changes
Very nice. Thank you! A few comments and suggestions.

2022-09-19 14:47 UTC, mr-tz commented on data-manipulation/compression/compress-data-using-lzo.yml
> +        - number: 0xBFFE
```suggestion
        - or:
          - number: 0xBFFE
          - number: 0xBFFF
```

2022-09-19 14:47 UTC, mr-tz commented on data-manipulation/compression/compress-data-using-lzo.yml
> +        - number: 0xBFFE
this may be more robust for another compiler

2022-09-19 14:47 UTC, mr-tz commented on data-manipulation/compression/decompress-data-using-lzo.yml
> +          - number: 0xFFFFFFFC
can you add a description of the respective instruction here? is this a sub that should be accounted for as another option?

2022-09-19 14:47 UTC, mr-tz commented on data-manipulation/compression/decompress-data-using-lzo.yml
> +    - or:
this `or` can be removed?

2023-01-02 17:30 UTC, mr-tz commented
Hey @edeca, can you provide input on my above comments and questions? I'd be happy to finish the rule or you can make the changes directly.

2023-01-30 14:42 UTC, mr-tz commented
continuing this in #677, thanks for the initial work @edeca

2023-01-30 14:42 UTC, closed without merging