Add capa rule load-code/shellcode/execute-shellcode-via-callback-functions.yml
mandiant/capa-rules pull request #744
Opened 2023-04-12 09:33 UTC by ejfocampo

2023-04-17 16:19 UTC, mike-hunhoff requested changes
Thank you @ejfocampo, looks great! I suggested minor changes then LGTM 🚀

2023-04-17 16:22 UTC, mike-hunhoff commented on load-code/shellcode/execute-shellcode-via-callback-functions.yml
> +        - api: EnumDateFormatsA
capa automatically handles Windows API functions ending in `A` and `W` so we can drop the `A` here and capa will detect both forms. Apply this to the APIs listed below.

2023-04-18 02:10 UTC, ejfocampo commented on load-code/shellcode/execute-shellcode-via-callback-functions.yml
> +        - api: EnumDateFormatsA
Omitted A and W on relevant APIs as suggested. Thanks for the tip @mike-hunhoff!

2023-04-18 05:44 UTC, ejfocampo commented on load-code/shellcode/execute-shellcode-via-callback-functions.yml
> +        - api: EnumUILanguagesA
I talked to the author of the rule - Jakub, and got the confirmation that we can merge the rules. Any guidance on how to proceed? Thanks

2023-04-19 01:23 UTC, ejfocampo commented on load-code/shellcode/execute-shellcode-via-callback-functions.yml
> +        - api: EnumUILanguagesA
Merged the two rules and deleted execute-shellcode-via-enumuilanguages.yml. Thanks

2023-04-19 15:55 UTC, mike-hunhoff approved these changes
looks great @ejfocampo , LGTM 🚀

2023-04-19 15:56 UTC, merged