Improve browser stealer & add SQLite lib detection
mandiant/capa-rules pull request #757
Opened 2023-05-11 09:47 UTC by Still34

## Summary

This PR adds detection for SQL statements related to cookie accesses, fixes one of the regexes, as well as adding rudimentary support for detection static sqlite3/cppsqlite3 lib linking. The relevant samples will be submitted to the test repo once I get the go ahead from the maintainers.

2023-05-11 19:42 UTC, williballenthin approved these changes
logic looks great, excited for the referenced file so we can merge this

thank you!

2023-05-12 10:43 UTC, mr-tz requested changes
Thanks! I've added comments to make the linter happy.

2023-05-12 10:43 UTC, mr-tz commented on linking/static/sqlite3/linked-against-cppsqlite.yml
Rename rule file to match the rule name, expected: "linked-against-cppsqlite3.yml", found: "linked-against-cppsqlite.yml"

2023-05-12 10:43 UTC, mr-tz commented on collection/browser/gather-chrome-based-browser-login-information.yml
> +      - 54390bda109aab7fc006b8b4ead5b6c2
can you include the offset here and in the other rule, please?

2023-05-15 15:45 UTC, mr-tz commented
from the linter:
```
  FAIL: rule string quotes incorrect: add double quotes to "/\\+(Edge|Chrome|Chromium|Brave\-Browser|YandexBrowser|Kometa|Orbitum|Dragon|Torch|Amigo)\\+User Data\\+Default(\\+Network)?\\+(Cookies|Login Data)/i"
```

2023-05-15 15:46 UTC, mr-tz commented on collection/browser/gather-chrome-based-browser-login-information.yml
> -        - string: /\\(Edge|Chrome|Chromium|Brave\-Browser|YandexBrowser|Kometa|Orbitum|Dragon|Torch|Amigo)\\User Data\\Default\\Login Data/
I think we need `regex` here instead of `substring`?

2023-05-23 07:48 UTC, Still34 commented
Ah right, oops, accidentally used substring instead of string.

2023-05-26 08:35 UTC, mr-tz commented
Now, we get this from the linter:
`  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example`

2023-06-30 15:33 UTC, Still34 commented
Sorry for the stale PR - it looks like the linter passes the test locally for me though.

```
 capa-rules  py -3 "E:\repos\capa\scripts\lint.py" --thorough  --samples E:\repos\capa\tests\data -t "gather chrome based browser login information" .
INFO:lint:successfully loaded 799 rules
INFO:lint:collecting potentially referenced samples
linting rule: gather chrome based browser log...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.96rule/s]
INFO:lint:no lints failed, nice!
```

2023-07-06 08:02 UTC, mr-tz commented
It doesn't match for me. The function doesn't contain the SELECT strings. Can you double check what's off?

2023-08-08 14:01 UTC, Still34 commented
After having a headache trying to figure out what went wrong for 30 minutes, finally figured out what was causing it to not match - it was due to the default scope the previous rule used, switching to `file` fixed it. It should pass the linter now *hopefully*.

2023-08-09 08:22 UTC, mr-tz approved these changes
looks good, thank you!

2023-08-19 09:36 UTC, merged