Add detection rule for hp-socket linking
mandiant/capa-rules pull request #848
Opened 2023-11-22 04:41 UTC by Still34

2023-11-22 12:44 UTC, mr-tz approved these changes
thanks, once we have a test sample, this is good to go

2023-11-22 18:05 UTC, mike-hunhoff approved these changes
Awesome!

2023-12-13 16:01 UTC, yelhamer requested changes

2023-12-13 16:01 UTC, yelhamer commented on linking/static/hp-socket/linked-against-hp-socket.yml
> +    scope: file
capa now has initial support for dynamic analysis. So rules must provide their scopes in both static (file, function, basic block, instruction, or unsupported) and dynamic (file, process, thread, call, or unsupported) analysis flavors. Please check the updated [doc/format.md](https://github.com/mandiant/capa-rules/blob/master/doc/format.md#meta-block) for more info :]

Please consider the following suggestion:
```suggestion
    scopes:
      static: file
      dynamic: file
```

2023-12-14 19:21 UTC, yelhamer approved these changes
Thanks!

2024-01-17 08:22 UTC, mr-tz commented
I wasn't able to find a sample that matches AND is quick to analyze for testing. Can we move this to the nursery for now?

2024-01-22 05:48 UTC, Still34 commented
Is that something you'd like me to do? Move the file to the nursery section?

2024-01-22 09:54 UTC, mr-tz commented
Yes, please, if you can.

2024-01-23 09:41 UTC, merged

2024-01-23 09:41 UTC, mr-tz commented
thank you!