added detections for reading/writing shadow file, password database
mandiant/capa-rules pull request #949
Opened 2024-10-24 15:30 UTC by jlmndt

added detections for reading/writing shadow file, password database

2024-10-24 15:49 UTC, williballenthin requested changes
thank you!

2024-10-24 15:49 UTC, williballenthin commented on nursery/get-password-database-entry-on-linux.yml
>        static: basic block
let's make this `instruction` and same with the other rules, since they each only look for a single call instruction.

2024-10-24 15:49 UTC, williballenthin commented on nursery/get-shadow-password-file-entry-on-linux.yml
> +    name: get shadow password file entry on linux
please capitalize "Linux" in the rule metadata

2024-10-29 19:34 UTC, williballenthin approved these changes

2024-10-30 15:18 UTC, mr-tz approved these changes

2024-10-30 15:19 UTC, merged